library(ggplot2)
Andes <- read.delim("Andean_indF", header=F)
head(Andes)
Andes["pop"] <- rep("Andes", 5)
SA_Lowland <- read.delim("SALowland_indF", header=F)
head(SA_Lowland)
SA_Lowland["pop"] <- rep("SA_Lowland", 6)
Mex_Lowland <- read.delim("MexLowland_indF", header=F)
head(Mex_Lowland)
Mex_Lowland["pop"] <- rep("Mex_Lowland", 5)
Mex_Highland <- read.delim("MexHighland_indF", header=F)
head(Mex_Highland)
Mex_Highland["pop"] <- rep("Mex_Highland", 6)
SW_US <- read.delim("SWus_indF", header=F)
head(SW_US)
SW_US["pop"] <- rep("SW_US", 6)
Gua_Highland <- read.delim("GuaHigh_indF", header=F)
head(Gua_Highland)
Gua_Highland["pop"] <- rep("Gua_Highland", 3)
combine <- rbind(Andes, SA_Lowland, Mex_Highland, Mex_Lowland, SW_US, Gua_Highland)
combine
combine <- combine[-14, ]
combine
names(combine)[1] <- "ind_F"
head(combine)
colorder <- c( "Andes", "SA_Lowland", "Mex_Highland", "Mex_Lowland", "SW_US", "Gua_Highland")
ggplot(data=combine, aes(x=pop, y=ind_F)) + geom_boxplot(aes(fill=pop)) + xlab("")  + scale_x_discrete(limits=colorder,labels=c("Andes","SA_Low","MexHigh","MexLow", "SW_US", "GuaHigh")) + theme_bw()
ggsave("inbreedingCoefficient.boxplot.pdf")
ggplot(data=combine, aes(x=pop, y=ind_F)) + geom_boxplot(aes(fill=pop)) + xlab("")  + scale_x_discrete(limits=colorder,labels=c("Andes","SA_Low","MexHigh","MexLow", "SW_US", "GuaHigh")) + theme_bw() + ylab("Inbreeding Coefficient")
ggsave("inbreedingCoefficient.boxplot.pdf")
ggplot(data=combine, aes(x=pop, y=ind_F)) + geom_boxplot(aes(fill=pop)) + xlab("")  + coord_cartesian(ylim = c(0, 0.003)) + scale_x_discrete(limits=colorder,labels=c("Andes","SA_Low","MexHigh","MexLow", "SW_US", "GuaHigh")) + theme_bw() + ylab("Inbreeding Coefficient")
ggsave("inbreedingCoefficient.boxplot.pdf")
ggplot(data=combine, aes(x=pop, y=ind_F)) + geom_boxplot(aes(fill=pop)) + xlab("")  + coord_cartesian(ylim = c(0, 0.002)) + scale_x_discrete(limits=colorder,labels=c("Andes","SA_Low","MexHigh","MexLow", "SW_US", "GuaHigh")) + theme_bw() + ylab("Inbreeding Coefficient")
ggsave("inbreedingCoefficient.boxplot.pdf")
savehistory("inbreedingCoefficient.boxplot.R")
