library(ggplot2)
df <- read.delim("numOfDerivedHomoSites.txt")
head(df)
summary(df$percentage)
levels(df$pop)
colorder <- c( "Andes", "SA_Lowland", "Mex_Highland", "Mex_Lowland", "SW_US", "Gua_Highland")

ggplot(data=df, aes(x=pop, y=percentage)) + geom_boxplot(aes(fill=pop)) + xlab("") + coord_cartesian(ylim = c(0.0024, 0.0028)) + scale_x_discrete(limits=colorder,labels=c("Andes","SAlow","MexHigh","MexLow", "swUS", "GuaHigh")) + theme_bw() + ylab("percentage of derived homozygous sites")
ggsave("numOfDerivedHomoSites.corrected.boxplot.pdf")

head(df)
summary(df$no.derived.homo.sites)
ggplot(data=df, aes(x=pop, y=no.derived.homo.sites)) + geom_boxplot(aes(fill=pop)) + xlab("") + coord_cartesian(ylim = c(3382000, 3634000)) + scale_x_discrete(limits=colorder,labels=c("Andes","SAlow","MexHigh","MexLow", "swUS", "GuaHigh")) + theme_bw()
ggsave("numOfDerivedHomoSites.boxplot.pdf")

Andes <- subset(df, pop=="Andes")
Mex_Highland <- subset(df, pop=="Mex_Highland")
wilcox.test(Andes$percentage, Mex_Highland$percentage, alternative="greater")
Mex_Lowland <- subset(df, pop=="Mex_Lowland")
SA_Lowland <- subset(df, pop=="SA_Lowland")
SW_US <- subset(df, pop=="SW_US")
Gua_Highland <- subset(df, pop=="Gua_Highland")
wilcox.test(Andes$percentage, Mex_Lowland$percentage, alternative="greater")
wilcox.test(Andes$percentage, SA_Lowland$percentage, alternative="greater")
wilcox.test(Andes$percentage, Gua_Highland$percentage, alternative="greater")
wilcox.test(Andes$percentage, SW_US$percentage, alternative="greater")

wilcox.test(Mex_Highland$percentage, SW_US$percentage, alternative="greater")
wilcox.test(Mex_Highland$percentage, SA_Lowland$percentage, alternative="greater")
wilcox.test(Mex_Highland$percentage, Mex_Lowland$percentage, alternative="greater")
wilcox.test(Mex_Highland$percentage, Gua_Highland$percentage, alternative="greater")
wilcox.test(SA_Lowland$percentage, Gua_Highland$percentage, alternative="greater")
wilcox.test(SA_Lowland$percentage, Mex_Lowland$percentage, alternative="greater")
wilcox.test(SA_Lowland$percentage, SW_US$percentage, alternative="greater")
wilcox.test(Mex_Lowland$percentage, SW_US$percentage, alternative="less")
wilcox.test(Mex_Lowland$percentage, Gua_Highland$percentage, alternative="greater")
wilcox.test(SW_US$percentage, Gua_Highland$percentage, alternative="greater")
savehistory("percentOfDerivedHomo.R")
